# Generated by Django 4.1.1 on 2022-09-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='files/covers'),
        ),
    ]
